### PR TITLE
Add data from external lightning sensor WH57

### PR DESCRIPTION
**Pull request by pdostal**
Good evening,

thank you for your great software, I use Ecowitt just few hours but Prometheus integration would be showstopper for me.
Besides [WS69](https://shop.ecowitt.com/products/ws69) outdoor unit and [WN1980_C](https://shop.ecowitt.com/products/wn1980_c) console I bought also [WH57](https://shop.ecowitt.com/products/wh57) lightning sensor. You can find the PDF manual [here](https://www.ecowitt.com/api/quickstart/product?id=64&_gl=1*2a3x32*_ga*MzE0Njk0NC4xNjkxMDAwMDc2*_ga_4EK9KDRE8Q*MTY5MTAxMDUwOS4yLjEuMTY5MTAxMTIyNS41MS4wLjA.).

There is last lightning timestamp which I decided to ignore, numbers of lightnings per day and last lightning distance which in my case is in kilometers.

Please let me know if something is not up to your expectations and I will be happy to further tweak this pull request.

Once again thank you very much

Pavel

### CODE REVIEW

**Comment by djjudas21** [comment]
Hey :slightly_smiling_face: This is excellent, thanks. Just a small tweak - please could you document `DISTANCE_UNIT` in `README.md` and include sample output of the new Prometheus metrics, and then I will be happy to accept the PR. I'll roll a new release of the Docker image and update the Helm chart, too.

I'd be interested to hear how you get on with the WH57 lightning sensor - I was considering buying one myself :zap:

**Comment by pdostal** [comment]
Done.

I will let you know after we have some thunderstorm.

**Comment by djjudas21** [comment]
Thanks for your contribution. I've merged it and tagged release v0.4.0, plus an updated Helm chart

**Comment by pdostal** [comment]
Hello Jonathan,

here is my report:

the following graph shows `# HELP lightning_num Lightning daily count` for the last 30 days and we had thunderstorm at night from Aug 16 to Aug 17 and quicker Aug 26 evening:
image

See also more detailed graphs for each event where left one is `# HELP lightning_km Lightning distance` and right one `# HELP lightning_num Lightning daily count`:
image
image

Please note that the sensor is placed inside in our family house in the upper floor but not even close to the window.

So as amateur I'm happy with the result!

**Comment by djjudas21** [comment]
Thanks for sharing :smile: It's cool how you can detect lightning >30km away. And I had no idea there would be so many strikes in one storm. Do you know why the the distance seems to default to 20km when there is no activity?

**Comment by pdostal** [comment]
I don't. It can be of course workarounded in Grafana. I will try to experiment with it and report back if I have proper solution.

**Pull request merged**
